
package web.service.implementation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import web.service.ObjectFactory;
import web.service.WalletResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WalletService", targetNamespace = "http://service.web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WalletService {


    /**
     * 
     * @param walletID
     * @param moneyQnt
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/putMoneyOnBalanceRequest", output = "http://service.web/WalletService/putMoneyOnBalanceResponse")
    public WalletResponse putMoneyOnBalance(
        @WebParam(name = "wallet_ID", partName = "wallet_ID")
        int walletID,
        @WebParam(name = "money_Qnt", partName = "money_Qnt")
        double moneyQnt);

    /**
     * 
     * @param walletID
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/getBalanceOfCurrentWalletRequest", output = "http://service.web/WalletService/getBalanceOfCurrentWalletResponse")
    public WalletResponse getBalanceOfCurrentWallet(
        @WebParam(name = "wallet_ID", partName = "wallet_ID")
        int walletID);

    /**
     * 
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/addNewWalletRequest", output = "http://service.web/WalletService/addNewWalletResponse")
    public WalletResponse addNewWallet();

    /**
     * 
     * @param walletID
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/deleteWalletByIdRequest", output = "http://service.web/WalletService/deleteWalletByIdResponse")
    public WalletResponse deleteWalletById(
        @WebParam(name = "wallet_ID", partName = "wallet_ID")
        int walletID);

    /**
     * 
     * @param walletID
     * @param goodPrice
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/buyGoodRequest", output = "http://service.web/WalletService/buyGoodResponse")
    public WalletResponse buyGood(
        @WebParam(name = "wallet_ID", partName = "wallet_ID")
        int walletID,
        @WebParam(name = "good_price", partName = "good_price")
        double goodPrice);

    /**
     * 
     * @param walletID
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/getWalletByIdRequest", output = "http://service.web/WalletService/getWalletByIdResponse")
    public WalletResponse getWalletById(
        @WebParam(name = "wallet_ID", partName = "wallet_ID")
        int walletID);

    /**
     * 
     * @return
     *     returns WalletResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/WalletService/getAllWalletsRequest", output = "http://service.web/WalletService/getAllWalletsResponse")
    public WalletResponse getAllWallets();

}
